RunnersBlogMVC/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.DTO;
using System.Diagnostics.CodeAnalysis;
using DataAccessLayer.Models.Items;
using RunnersBlogMVC.Services.ItemsServices;

namespace RunnersBlogMVC.Controllers
{
    [ExcludeFromCodeCoverage]
    public class ItemsController : Controller
    {
        private readonly IItemsService itemService;
        private readonly CancellationToken cancellationToken;
        public ItemsController(IItemsService itemService)
        {
            this.itemService = itemService;
            cancellationToken = new CancellationToken();
        }
        // GET /items/createItem
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteItemAsync(Guid id)
        {
            return await itemService.MiddlePageAsync(id, cancellationToken);
        }
        public async Task<IActionResult> UpdateItemAsync(Guid id)
        {
            return await itemService.MiddlePageAsync(id, cancellationToken);
        }
        // GET /items/createItem
        [HttpGet]
        [Authorize(Roles = "Admin,User")]
        public IActionResult CreateItem()
        {
            return View();
        }
        //GET /items/getAllItems
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetAllItemsAsync()
        {
            return await itemService.GetAllAsync(cancellationToken);

        }
        //POST /createItem/Item/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> CreateItemAsync(ItemDto itemDto)
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await itemService.CreateAsync(email, itemDto, cancellationToken);
        }
        //PUT /items/editItem/{id}
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateByIdAsync(Guid id, ItemDto itemDto)
        {
            return await itemService.UpdateByIdAsync(id, itemDto, cancellationToken);
        }
        //DELETE /items/deleteItem/{id}
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult<Item>> DeleteByIdAsync(Guid id)
        {
            return await itemService.DeleteByIdAsync(id, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> OrderItemsAsync(string sortOrder)
        {
            return await itemService.GetOrderedItemsAsync(sortOrder, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ReserveItemAsync(Guid id)
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await itemService.ReserveItemAsync(email, id, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ReservedItemsListAsync()
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await itemService.ReservedItemsListAsync(email, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> CancelReservedItemAsync(Guid id)
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await itemService.CancelReservedItemAsync(email, id, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> BuyReservedItemAsync(Guid id)
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await itemService.BuyReservedItemAsync(email, id, cancellationToken);
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> SearchItemAsync(string searchBy)
        {
            return await itemService.SearchItemAsync(searchBy, cancellationToken);
        }
    }
}

RunnersBlogMVC/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using RunnersBlogMVC.Services.ProfileServices;

namespace RunnersBlogMVC.Controllers
{
    [ExcludeFromCodeCoverage]
    public class ProfileController : Controller
    {
        private readonly IProfileService profileService;
        private readonly CancellationToken cancellationToken;
        public ProfileController(IProfileService profileService)
        {
            this.profileService = profileService;
            cancellationToken = new CancellationToken();
        }
        public IActionResult UserProfile()
        {
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> UserProfileAsync()
        {
            var email = HttpContext.User.Claims.Where(c => c.Type.Contains("emailaddress"))?.FirstOrDefault()?.Value;
            if (email is null)
            {
                return RedirectToAction("LoginUser", new RouteValueDictionary(new { Controller = "Login", Action = "LoginUser" }));
            }
            return await profileService.UserProfileAsync(email, cancellationToken);
        }
    }
}

RunnersBlogMVC/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.Models;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using RunnersBlogMVC.Services.RoleServices;

namespace RunnersBlogMVC.Controllers
{
    [ExcludeFromCodeCoverage]
    public class RoleController : Controller
    {
        private readonly IRoleService roleService;
        public RoleController(IRoleService roleService)
        {
            this.roleService = roleService;
        }
        public IActionResult CreateRoleAsync()
        {
            return View();
        }
        //Post: User/CreateRole
        [HttpPost]
        // [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateRole([Required][EmailAddress] string email, UserRole userRole)
        {
            return await roleService.CreateRole(email, userRole);
        }
    }
}

RunnersBlogMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DataAccessLayer.Models;
using System.Diagnostics.CodeAnalysis;
using RunnersBlogMVC.Services.UserService;

namespace RunnersBlogMVC.Controllers
{
    [ExcludeFromCodeCoverage]
    public class UserController : Controller
    {
        private readonly IUserService userService;
        public UserController(IUserService userService)
        {
            this.userService = userService;
        }
        public IActionResult CreateUser()
        {
            return View();
        }
        //Post : User/CreateUser
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> CreateUser(User user)
        {
            return await userService.CreateAsync(user, CancellationToken.None);
        }
    }

}

RunnersBlogMVC/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Access Denied</h1>

RunnersBlogMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RunneShop</title>
    <link rel="stylesheet" href="~/css/superhero.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RunnersBlogMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RunneShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Items" asp-action="GetAllItems">Items</a>
                        </li>
                        @{
                            if (User?.Identity?.IsAuthenticated == true)
                            {
                             <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Profile" asp-action="UserProfile">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Items" asp-action="ReservedItemsList">Basket</a>
                            </li>                                
                            }
                        }

                        @*        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                            </li>*@
                    
                    </ul>
                    @{
                        if (User?.Identity?.IsAuthenticated == false)
                        {
                            <form class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="CreateUser">Register</a>
                            </form>
                            <form class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="LoginUser">Login</a>
                            </form>
                        }
                    }
                    @{
                        if (User?.Identity?.IsAuthenticated != false && User.IsInRole("Admin"))
                        {
                            <form class="nav-item">
                                <a style="float: left;" class="btn btn-light" asp-controller="Role" asp-action="CreateRole">Roles</a>
                            </form>
                            <form class="nav-item">
                                <u style="color: lightgray;">Welcome: @User.Identity.Name</u>
                                <a style="float: right;" class="btn btn-danger" asp-controller="Login" asp-action="Logout">Logout</a>
                            </form>
                        }
                        else if (User?.Identity?.IsAuthenticated != false)
                        {
                            <form class="nav-item">
                                <u style="color: lightgray;">Welcome: @User.Identity.Name</u>
                                <a style="float: right;" class="btn btn-danger" asp-controller="Login" asp-action="Logout">Logout</a>
                            </form>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RunnersBlogMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>